### ISSUE TITLE
Implement target reward mechanism for lead percentage rate

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/basilisk-crowdloan-query#5]
For the upcoming Hydra crowdloan, we want to revive the target mechanism we had in the very first Basilisk auction. This means that our rewards (bonus), will be calculated towards a target as usual. BUT this target won't always be the current auction winner, but instead a supposed winner of the *target* auction.

Right now the lead percentage rate is calculated between us & winner of the current auction, with the target mechanism enabled, it should compare our amount raised with the winner of the auction we're targeting.

Example:

- Current auction id: 1
- Target auction id: 2

Money raised:
- Para1: 100, Para2: 200, us: 50

Sibling/target in this case would be para1, since para2 is the supposed winner of the current auction (1), but we're targeting auction 2 which will be won by para1, so that our competitor.

This should be mostly implemented by changing how the lead percentage rate is calculated in the processor

**Comment by maht0rz** [comment]
One part of this task is to change the [following code](https://github.com/galacticcouncil/basilisk-crowdloan-query/blob/hydra/src/utils/incentive.ts#L137)

To use `.getMany` and utilize the `skip + take`  options, to select not just the first (winning) crowdloan as a sibling, but skip to the winning crowdloan of the target auction. So if we're in auction '1', and the target auction is '2', we'd theoretically do `skip: 1, take: 1` (or something like that)

**Comment by maht0rz** [comment]
`mostRecentAuctionId` also needs to be added to the chronicle at the `handleAuctionStarted` mapping, so that it can be compared with the target auction.

We need to think about the case where an auction has ended and a new auction has not started yet. In that case the old winner has been marked as having won an auction already, so they wont be included in the sibling query anymore.

This would mean if we miscalculate the skipping index for the sibling due to the outdated auction id, we'd not be siblings with the upcoming auction winner, but with an upcoming auction +1 for example. Solution to this is probably aritificailly incrementing the auction id after an auction ends. It will be automatically overwritten when the new auction starts - but this will cover our back in the period between auctions (which usually lasts for like an hour or two)

**Comment by timbo-timboa** [comment]
> `mostRecentAuctionId` also needs to be added to the chronicle at the `handleAuctionStarted` mapping, so that it can be compared with the target auction.
>

@maht0rz review here: https://github.com/galacticcouncil/basilisk-crowdloan-query/blob/c847473a05c5a97bc58bbf7a97220bc729448d6a/src/mappings/auction/handleAuctionStarted.ts#L19-L33

**Comment by timbo-timboa** [comment]
> 
> We need to think about the case where an auction has ended and a new auction has not started yet. In that case the old winner has been marked as having won an auction already, so they wont be included in the sibling query anymore.
> 
> This would mean if we miscalculate the skipping index for the sibling due to the outdated auction id, we'd not be siblings with the upcoming auction winner, but with an upcoming auction +1 for example. Solution to this is probably aritificailly incrementing the auction id after an auction ends. It will be automatically overwritten when the new auction starts - but this will cover our back in the period between auctions (which usually lasts for like an hour or two)

@maht0rz review proposed solution here: 

https://github.com/galacticcouncil/basilisk-crowdloan-query/blob/d8eeabf714f23bea070c5f1e931eb6614aceaf35/src/mappings/auction/handleAuctionClosed.ts#L29-L39

**Comment by timbo-timboa** [comment]
> One part of this task is to change the [following code](https://github.com/galacticcouncil/basilisk-crowdloan-query/blob/hydra/src/utils/incentive.ts#L137)
> 
> To use `.getMany` and utilize the `skip + take` options, to select not just the first (winning) crowdloan as a sibling, but skip to the winning crowdloan of the target auction. So if we're in auction '1', and the target auction is '2', we'd theoretically do `skip: 1, take: 1` (or something like that)

@maht0rz see target mechanism,  to target sibling parachain that is in line to compete with us for our target Auction,  here:

https://github.com/galacticcouncil/basilisk-crowdloan-query/blob/79b5217f8584ab626311439c3b9804c2782f385f/src/utils/incentive.ts#L128-L179
